# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bread From Heaven Christian Fellowship
email: info@breadfromheaven.org
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Bread From Heaven Christian Fellowship
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:title/
twitter_username: jekyllrb
github_username:  jekyll
facebook_url: https://www.facebook.com/bfhcf
youtube_channel_url: https://www.youtube.com/bfhcf
youtube_api_key: AIzaSyADnoqPB_iM1Q2qhtbCe64x3HS4fB903z0
podcast_api_key: f3f01cb7cc23bb7b308833bab0f18db9
google_analytics: G-H0HGBG8D6D

address: Concha Cruz corner Poblete St. (Phase V)
city: BF Homes, Las Pi√±as, Philippines
tel_number: +63 2 8807 5689
tel_number2: +63 917 628 4715

# Cloudinary configuration
cloudinary:
  cloud_name: bfhcf
  base_url: https://res.cloudinary.com/bfhcf/image/upload

# Legacy Cloudinary URLs (deprecated - kept for backward compatibility)
logo_url: https://res.cloudinary.com/bfhcf/image/upload/logos
ministry_logo_url: https://res.cloudinary.com/bfhcf/image/upload/logos/ministries
ministry_logo_thumbnail_url: https://res.cloudinary.com/bfhcf/image/upload/c_scale,w_500/logos/ministries
church_images_url: https://res.cloudinary.com/bfhcf/image/upload/church
monthly_themes_images_url: https://res.cloudinary.com/bfhcf/image/upload/monthly-themes
other_images_url: https://res.cloudinary.com/bfhcf/image/upload/others
member_images_url: https://res.cloudinary.com/bfhcf/image/upload/members
devotion_images_url: https://res.cloudinary.com/bfhcf/image/upload/devotions
events_images_url: https://res.cloudinary.com/bfhcf/image/upload/c_scale,w_594/events
events_images_full_url: https://res.cloudinary.com/bfhcf/image/upload/c_scale,w_1440/events
books_images_url: https://res.cloudinary.com/bfhcf/image/upload/books

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  sass_dir: assets/css

# Collections
collections:
  events:
    output: true
    permalink: /events/:title/
  devotions:
    output: true
    permalink: /devotions/:title/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
      category-name: "events"
  - scope:
      path: ""
      type: "devotions"
    values:
      layout: "devotion"
      category-name: "devotions"

navigation:
  - text: Home
    url: /
    icon: zmdi-home
    data_name: home
  - text: Events
    url: /events/
    icon: zmdi-calendar
    data_name: events
  - text: Sermons
    url: /sermons/
    icon: zmdi-videocam
    data_name: sermons
  - text: Projects
    icon: zmdi-favorite
    data_name: projects
    navtabs:
      - text: Books
        url: /books/courage-in-chaos
        icon: zmdi-book-image
        data_name: books
        submenus:
          - text: 5-Minute Journey
            url: /books/5-minute-journey
            icon: zmdi-book-image
          - text: Courage in Chaos
            url: /books/courage-in-chaos
            icon: zmdi-book-image
          - text: Losing Spiritual Vitality
            url: /books/losing-spiritual-vitality
            icon: zmdi-book-image
      - text: Podcasts
        url: /podcasts/poimenally-yours
        icon: zmdi-hearing
        data_name: podcasts
        submenus:
          - text: Poimenally Yours
            url: /podcasts/poimenally-yours
            icon: zmdi-hearing
          - text: Bread Talks
            url: /podcasts/bread-talks
            icon: zmdi-hearing
  - text: Ministries
    url: /ministries/
    icon: zmdi-view-compact
    data_name: ministries
  - text: Who We Are
    url: /who-we-are
    icon: zmdi-face
    data_name: who-we-are
    navtabs:
      - text: About Us
        url: /who-we-are
        icon: zmdi-face
      - text: Our Beliefs
        url: /our-beliefs
        icon: zmdi-book
      - text: Church History
        url: /church-history
        icon: zmdi-calendar
  - text: Give
    url: /give/
    icon: zmdi-money-box
    data_name: give
  - text: Contact
    url: /contact/
    icon: zmdi-phone
    data_name: contact


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
